services:
  db:
    image: postgres
    container_name: postgresDB
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_CONTAINER_PORT}
    volumes:
      - postgresDBData:/var/lib/postgresql/data
volumes:
  postgresDBData:
